SUFFIX=

include Makefile

.PHONY : clean
clean : 
	rm -f *.o $(SOURCES:.c=)

# Those depend on libm
Aliquot_sequence_classifications : Aliquot_sequence_classifications.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< -lm

Proper_divisors : Proper_divisors.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< -lm

